ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common


obj-$(CONFIG_MSMB_CAMERA) += laser_ST/
obj-$(CONFIG_MSMB_CAMERA) += laser_HEPTAGON/
obj-$(CONFIG_MSMB_CAMERA) += laser_library/
