ccflags-y += -Idrivers/media/platform/msm/camera_v2
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/io
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/cci
ccflags-y += -Idrivers/media/platform/msm/camera_v2/common
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_ST/inc
ccflags-y += -Idrivers/media/platform/msm/camera_v2/sensor/laser_focus/laser_library/inc

obj-$(CONFIG_MSMB_CAMERA) += msm_laser_ST_api.o
#obj-$(CONFIG_MSMB_CAMERA) += vl6180x_i2c.o
#obj-$(CONFIG_MSMB_CAMERA) += vl6180x_api.o

obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api.o
#obj-$(CONFIG_MSMB_CAMERA) += vl53l0_i2c_platform.o
obj-$(CONFIG_MSMB_CAMERA) += vl53l0_platform.o
#obj-$(CONFIG_MSMB_CAMERA) += vl53l0_platform_log.o
#obj-$(CONFIG_MSMB_CAMERA) += vl53l0_tuning.o

obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api_calibration.o
obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api_core.o
obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api_histogram.o
obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api_ranging.o
obj-$(CONFIG_MSMB_CAMERA) += vl53l0_api_strings.o



